name: Check

on:
  pull_request:
  push:
    branches: [ 'main' ]

permissions:
  contents: read

jobs:

  lf:
    name: Check LF on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate LF
        run: 	git ls-files --eol | grep --color=always -i '^i/[^lf|none]' && exit 1 || echo 'LF Ok'

  composer:
    name: Check composer on PHP ${{ matrix.php }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        php:
          - "8.2"
          - "8.3"
          - "8.4"
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none
      - name: Validate composer.json and composer.lock
        run: composer validate --strict
      - name: Audit composer
        run: composer audit
      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi
      - name: Normalize composer
        run: composer normalize --dry-run
      - name: Composer require checker
        run: vendor/bin/composer-require-checker
      - name: Composer unused
        run: curl -OL https://github.com/composer-unused/composer-unused/releases/latest/download/composer-unused.phar && php composer-unused.phar

  code-style:
    name: Check code style on PHP ${{ matrix.php }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        php:
          - "8.2"
          - "8.3"
          - "8.4"
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none
      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi
      - name: php-cs-fixer
        run: PHP_CS_FIXER_IGNORE_ENV=1 vendor/bin/php-cs-fixer --config=php-cs-fixer.php fix --dry-run --diff --ansi

  code-standard:
    name: Check code standard on PHP ${{ matrix.php }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        php:
          - "8.2"
          - "8.3"
          - "8.4"
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none
      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi
      - name: rector
        run: vendor/bin/rector process --config=rector.config.php --dry-run --ansi

  static-analysis:
    name: Check static analysis on PHP ${{ matrix.php }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        php:
          - "8.2"
          - "8.3"
          - "8.4"
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none
      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi
      - name: phpstan
        run: vendor/bin/phpstan analyse -c phpstan-config.neon --ansi
      - name: psalm
        run: vendor/bin/psalm --config=psalm.xml --output-format=github --shepherd --stats --no-cache

  tests:
    name: Check tests on PHP ${{ matrix.php }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        php:
          - "8.2"
          - "8.3"
          - "8.4"
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: pcov
      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi
      - name: phpunit
        run: vendor/bin/phpunit --configuration=phpunit.xml --coverage-text

  test-runtime-dependencies:
    name: Check runtime dependencies on PHP ${{ matrix.php }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        php:
          - "8.2"
          - "8.3"
          - "8.4"
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none
      - name: Install dependencies
        run: composer update --no-dev --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi
      - name: run test
        run: php test-runtime-dependencies.php
